version: '3'

services:
   frontend: 
      container_name: productivity_frontend
      build: ./ProdFrontend
      image: productivity_frontend
      restart: always
      #ports are exposed for debugging purposes
      ports:
         - 4200:4200
         - 49153:49153
      #mounts the sourcecode into the container, but excludes node_modules
      volumes:
         - "./ProdFrontend:/app"
         - "/app/node_modules"
      networks:
         - productivity_frontend_network

   
   backend:
      container_name: productivity_backend
      build: ./ProdBackend
      image: productivity_backend
      restart: always
      #ports are exposed for debugging purposes
      ports:
         - 3000:3000
         - 9229:9229
      #mounts the sourcecode into the container, but excludes node_modules
      volumes:
         - "./ProdBackend:/app"
         - "/app/node_modules"
      command: ["node_modules/nodemon/bin/nodemon", "--inspect=0.0.0.0", "./bin/www"]
      networks:
         - productivity_backend_network
      depends_on:
         - db


   nginx:
      container_name: productivity_nginx
      image: nginx
      restart: always
      ports: 
         - 80:80
         - 443:443
      volumes:
         - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      networks:
         - productivity_frontend_network
         - productivity_backend_network


   db:
      container_name: producitvity_db
      image: mysql:5.7.26
      restart: always
      command: --default-authentication-plugin=mysql_native_password
      #exposing ports for debugging purposes
      ports:
         - 3307:3306
      environment:
         MYSQL_DATABASE: productivity_db
         MYSQL_USER: admin
         MYSQL_PASSWORD: admin
         MYSQL_ROOT_PASSWORD: admin
      networks:
         - productivity_backend_network
      volumes:
         - ./mysql/data:/var/lib/mysql


networks:
   productivity_frontend_network:
   productivity_backend_network: