version: '3'

services:
   db-nutrition:
      container_name: producitvity_db_nutrition
      image: mysql:5.7.26
      restart: always
      command: --default-authentication-plugin=mysql_native_password
      ports:
         - 3308:3306
      environment:
         MYSQL_DATABASE: productivity_db_nutrition
         MYSQL_USER: admin
         MYSQL_PASSWORD: admin
         MYSQL_ROOT_PASSWORD: admin
      volumes:
         - ./data:/var/lib/mysql
         - ./init:/docker-entrypoint-initdb.d/:ro
         - ./init_data:/tmp/data

